### ISSUE TITLE
Connection error in test environment

### ISSUE THREAD

**Issue by herber-vasquez** [AuthorizeNet/sdk-dotnet#178] opened 2017-05-04 16:33 UTC
From the past three days I have been getting the following connection error in the test environment:

> Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

Here the full stack trace:

`2017-05-04 08:56:55.5946 [DEBUG] CS=AuthorizeNet.Util.HttpUtility.GetPostUrl: Creating PostRequest Url: 'https://apitest.authorize.net/xml/v1/request.api' 
2017-05-04 08:56:55.5946 [DEBUG] CS=AuthorizeNet.Util.HttpUtility.PostData: Retreiving Response from Url: 'https://apitest.authorize.net/xml/v1/request.api' 
2017-05-04 08:56:55.6102 [ERROR]  CS=ServiceStack.DtoUtils.CreateErrorResponse: ServiceBase<TRequest>::Service Exception Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.*   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)`

I'm using the version 1.9.2 of the library.

**Comment by iashaik** [comment] 2017-05-04 18:06
I was using an older version (1.8.9) and I actually came to see if this is resolved in 1.9.2 but your question answered it. 

The problem is that Authorize.NET have disabled SSL & TSL 1.0 and TSL 1.1 and only uses TSL 1.2. 

https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/TLS-1-1-and-1-0-Disabled-in-Sandbox-on-April-30-2017-Updated/ba-p/57726 

I think this package should have a solution to the problem instead of us having to change code.

**Comment by marioav** [comment] 2017-05-04 18:39
Seems to me this is more related to the .net framework than the library itself.
Here is more info: http://blogs.perficient.com/microsoft/2016/04/tsl-1-2-and-net-support/

I haven't tested it yet, but I'm working on it and I will report back.

**Comment by iashaik** [comment] 2017-05-04 18:53
Yes upgrading to 4.6 worked for me.

**Comment by marioav** [comment] 2017-05-04 19:03
In my case, using .net 4.5 the following line did the trick:

 ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

As is pointed out in the article previously shared.

**Comment by HughJeffner** [comment] 2017-05-09 19:19
So everyone with .net 4.0 / .net 3.5 without the ability to upgrade the application to 4.5 is pretty much screwed then?

**Comment by iashaik** [comment] 2017-05-09 19:24
Well you can set `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;` and be done with it. 

But the problem with that is if your app is communicating with other server that uses SSL would cause issues. 

But this could help http://stackoverflow.com/questions/26160118/net-https-requests-with-different-security-protocols-across-threads

**Comment by HughJeffner** [comment] 2017-05-10 15:04
In my case we are using a legacy web service using TLS 1.0 that will never be upgraded.  I ended up upgrading the framework of our application to 4.5 and using the following line to enable TLS 1.2 with older versions as a fallback:

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;`

By enabling all 3 the system can decide the appropriate version to use.  I confirmed by using wireshark a TLS 1.2 connection was established with Authorize.net and a TLS1.0 connection with the legacy web service.

**Comment by Purushottamlpa** [comment] 2017-12-14 11:08
Thank you for raising this issue. We have had some releases since the issue was raised, and we hope that these updates have resolved your asks. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.

**Closed** 2017-12-14 11:39 UTC
