### ISSUE TITLE
defaultPaymentProfile flag does not work

### ISSUE THREAD

**Issue by whiskeysauer** [AuthorizeNet/sdk-dotnet#183] opened 2017-06-15 12:43 UTC
When creating a new customer payment profile and I set defaultPaymentProfile = true, the payment profile does not show as being default. The creation of the new profile does work. However, if I query all cards for the customer, they are all set to false on the defaultPaymentProfile property.

I have not tried setting it using the update method. That's my next step. Also... I don't know if it DOES set it, but when asking for all payment profiles the API does not set that property on the default method (which is a major flaw if you ask me). I will also try getting the value by querying the customer and see if a default payment profile is returned.

For a quick walk-through of what I am seeing.. please view this...
[https://gtma.s3.amazonaws.com/videos/2017-06-15-2009-06_720p.mp4](https://gtma.s3.amazonaws.com/videos/2017-06-15-2009-06_720p.mp4)

**Comment by gnongsie** [comment] 2017-06-15 13:21
Hi, 
This is a duplicate of [this issue](https://github.com/AuthorizeNet/sdk-php/issues/230).

As explained in that issue, 
The **`CreateCustomerProfile API`** does **not** allow you to set the default profile and the **`GetCustomerProfile API`** does **not** return the default profile. I have corrected my comments to reflect the same.

For setting the customer profile, you have to use
1. [**`CreateCustomerPaymentProfile API`**](http://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-payment-profile) or 
2. [**`UpdateCustomerPaymentProfile API`**](http://developer.authorize.net/api/reference/index.html#customer-profiles-update-customer-payment-profile) or 
3. [**`Create a Customer Profile from a Transaction API`**](http://developer.authorize.net/api/reference/index.html#customer-profiles-create-a-customer-profile-from-a-transaction)


For retrieving this same information, you have to use 
1. [**`Get Customer Payment Profile API`**](http://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-payment-profile) or
2. [**`Get Customer Payment Profile List API`**](http://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-payment-profile-list)

Also the team has been notified of this. Steps are underway to address this.

**Comment by whiskeysauer** [comment] 2017-06-15 13:32
Yes, I saw that issue. But you are mistaken...

That's what I am doing. I am NOT using the "Create Customer Profile" method. I AM using the "Create Customer Payment Profile" method. I am setting on that method (which is documented) the defaultPaymentProfile to true. That is the part that does not work. Or it seems not to work. That is why I even made a video to prove this. I am NOT (I repeat NOT) using the Create Customer Profile. I don't know why everyone I have shown this seems to assume I am using the "Create Customer Profile". I am not. The customer profile (in my example video) is already created.

After creating the "Customer **Payment** Profile", I try to verify if it works... I AM using the "Get Customer Profile List" - just like you point out. All profiles returned show the defaultPaymentProfile to be false.

So... is there a way that this does work?

**Comment by whiskeysauer** [comment] 2017-06-15 13:37
Okay... I see your comment here.... This may be the issue. You are saying that when asking for the list of profiles, this will NOT tell us which one is the default? If that is the case, then perhaps my API call is working, but I simply can't see which one is the default using that API call. Can you just confirm that? Thanks.


> I'd like to clarify how the Get Customer Payment Profiles API works. A single customer profile can have only one default payment profile, which is set by the merchant. The API returns a TRUE value in a field defaultPaymentProfile within a payment profile, if that payment profile has been set as the default; otherwise it will not be present for the profile. It does not send TRUE or FALSE for all profiles.
> Kindly refer to the documentation here for clarity.

**Comment by gnongsie** [comment] 2017-06-15 13:54
The issue is not with how you are setting the default payment profile; but rather how you are retrieving the information again.

In your video, you are using the **`Get Customer Profile API`** to query back the information about the profile you just created. This API will not return the actual value of the `defaultPaymentProfile` tag.

If you change your code to use the **`Get Customer Payment Profile API`** or the **`Get Customer Payment Profile List API`**, you would be able to get the expected value of the `defaultPaymentProfile` tag (**TRUE** if it is set).

**Closed** 2017-12-14 11:37 UTC

**Comment by danielricecodes** [comment] 2019-06-20 16:09
Wow.  So much pain caused by a simple error in the Ruby SDK sample code.

FYI - the Ruby sample code for this shows that one can set this flag in the Create Customer Profile...however according to @gnongsie this is not true.  The Sample Code needs to be updated.

See: https://developer.authorize.net/api/reference/#customer-profiles-create-customer-profile

I will adjust my code to send TWO requests...create profile, then create customer profile.  I am hoping this will work as I need to set the default card in my app.

**Comment by kikmak42** [comment] 2019-06-21 08:27
@danielricecodes  sorry for the inconvenience you had, we updated the sample codes in ruby and csharp accordingly

**Comment by danielricecodes** [comment] 2019-06-21 12:43
@kikmak42 - it would be great if this inconsistency in the Authorize.net API itself were corrected.  I know this isn't actually a problem with the SDK's, but rather with the API and consistency across endpoints.  How would I go about logging a feature request with the Authorize.net Development team?
