### ISSUE TITLE
Could not create SSL/TLS secure channel (First attempt only)

### ISSUE THREAD

**Issue by valmont** [AuthorizeNet/sdk-dotnet#234] opened 2018-09-18 18:08 UTC
**Description:** After the application pool restarts, the first attempted transaction receives the `Could not create SSL/TLS secure channel`. After this, the order processing functions as expected.

**SDK Version:** 1.9.5
**.NET Version:** 4.5

**Calling Code:**

```c#
...
  var transactionRequest = new transactionRequestType {
    transactionType = transactionType.ToString(),
    amount = Math.Round(context.GrandTotal, 2, MidpointRounding.AwayFromZero),
    profile = profileToCharge,
    tax = tax,
    shipping = shipping,
    order = new orderExType {
      invoiceNumber = context.OrderID.ToString()
    },
    customerIP = context.ClientIp
  };

  var request = new createTransactionRequest { transactionRequest = transactionRequest };

  // instantiate the collector that will call the service
  var controller = new createTransactionController(request);
  controller.Execute();

  //Use the old transaction result object so all
  //calling code still behaves as expected
  var result = new CreditCardTransaction();

  // get the response from the service (errors contained if any)
  var response = controller.GetApiResponse();
...
```

**Comment by jmedved17** [comment] 2018-10-12 13:30
I'm also seeing that. do you know if it was addressed in 1.9.6?

**Comment by cforbesywam** [comment] 2019-02-05 19:04
I am also seeing this issue using Authorize.Net own library sdk-dotnet off of GitHub using the master branch after v1.9.7.  The unit test for SampleCodeCreateTransaction fails but the other unit tests following this one pass.  However whenI change the order of the unit tests SampleCodeCreateTransaction  passes as long as it is not the first unit test called!
![testrun1](https://user-images.githubusercontent.com/10047139/52296911-bef4c680-293c-11e9-911e-c0d8c1bf8674.png)
![testrun2](https://user-images.githubusercontent.com/10047139/52296913-bef4c680-293c-11e9-8072-f470c92129f6.png)

Testing on Win 10  Ent x64 (Version 1809) Build 17763.253

**Comment by cforbesywam** [comment] 2019-02-06 23:23
I know what the issue is now and how to solve it.

// Set Tls to Tls1.2
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; // | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

Must come before the HttpWebRequest is defined / created.

That is why it fails the first time but subsequent requests work.  After the first request fails by then it has correctly set the Protocol to TLS 1.2 when it creates the next web request.

The solution is to move the TLS 1.2  BEFORE the any web request (HttpWebRequest) is created.
I believe there are at least two places in the code base where this change needs to take place.

In:
HttpUtility.cs
ANetApiResponse PostData<TQ, TS>(AuthorizeNet.Environment env, TQ request) 

and 
HttpXmlUtility.cs
ANetApiResponse Send(ANetApiRequest apiRequest)

**Comment by jmedved17** [comment] 2019-02-06 23:40
Well that makes perfect sense now that you mentioned it. No more error.   THANK YOU

**Comment by pmacapal** [comment] 2019-02-07 03:16
@cforbesywam, many thanks to tracking and providing the fix for this. ^_^

> // Set Tls to Tls1.2
> ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; // | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
> 

How about setting it to something like below (so as not to affect connections to legacy services in the AppDomain)? Or, can this setting be removed from Authorize.Net SDK and let the application set the security protocol to use?

ServicePointManager.SecurityProtocol = _ServicePointManager.SecurityProtocol_ | SecurityProtocolType.Tls12; // | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

**Comment by cforbesywam** [comment] 2019-02-07 16:09
Since this is the Authorize.net code and the I believe the minimum requirement for most gateways is TLS 1.2 I would suggest keeping things as their are or uncomment the out the support for TLS 1.1 and 1.0 if legacy support is needed however you can always change the SecurityProtocol setting before doing the callout on the Legacy systems in your own code and then the AuthorizeNet library will simply change it back before it makes another request to the gateway - I thing that would be a better solution then trying to downgrade the AN library which could cause connection issues.

**Comment by gnongsie** [comment] 2019-03-06 09:36
Hi,

The latest version of the SDK has merged a fix for this issue (Thanks @cforbesywam).

Kindly test with the latest SDK and let us know if the issue still persists.

**Comment by cforbesywam** [comment] 2019-03-06 15:53
Hello Gabriel,

I’ve updated the AuthorizeNet package and all my unit tests are now passing which was NOT happening on before this edition.  So I can confirm this has fixed the issue!

Thank you for releasing this fix.

Blessings,


Colin Forbes
Research & Information
Part of the YWAM global family of ministries

**Comment by gnongsie** [comment] 2019-03-13 05:46
Thank you for raising this issue. Your continued support is appreciated.

I'll be closing this issue. Feel free to raise an issue if you face any other issues.

**Closed by gnongsie** 2019-03-13 05:46 UTC
Labels: awaiting-reply
