### ISSUE TITLE
Controller: Create Profile from transaction

### ISSUE THREAD

**Issue by tig4647** [AuthorizeNet/sdk-dotnet#62] opened 2015-01-26 13:59 UTC
This works well, except that when the profile is created the original transaction is not associated to the new profile. Also the system creates the billing address as a new shipto address which is not something I would personally desire as it may be a billing address only.

**Comment by brianmc** [comment] 2015-02-09 17:15
The original transaction will not be associated with the new profile because that transaction was not created with that profile, that's expected behavior.  On the shipping address I agree that's probably not what callers expect.  We'll look at this one for a future release.

**Comment by tig4647** [comment] 2015-02-12 20:40
I understand why it is not associate, but I could forsee an issue for those of us using CIM. When I process a refund, I tend to pass the CustomerProfileID andPaymentProfileID along with the transactionID and this would cause a fail. The developer would have to know that the first transaction should not be stored as a CIM transaction in their system but treated as a standard charge. I guess ultimately it depends on how the developer integrates the CIM.

**Comment by gnongsie** [comment] 2018-10-10 10:29
Hi,

As @brianmc has stated, the original transaction cannot be associated to the new profile and this is expected behavior.

On the other issue, we have tried to reproduce the issue. But we are not able to reproduce it now. As per our testing, the billing address in the transaction is always mapped to a billing address in the customer profile.

I am closing this issue based on this. Kindly reopen this if the issue is not fixed.

**Closed by gnongsie** 2018-10-10 10:29 UTC
